theme: just-the-docs
title: Janko.js
description: A progressive Telegram Bots framework.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - overview/FIRST_STEPS.md
  